### ISSUE TITLE
Refactor plugin to use latest version of IF

### ISSUE THREAD

**Issue by moin-oss** [moin-oss/datadog-importer#18]
This plugin in its current state is not compatible with the current version of the Impact Framework.  See: https://github.com/Green-Software-Foundation/if/blob/7011a2c7563cdfe4c09664e86c923ef83922cf1b/Refactor-migration-guide.md for specifics.  Update this plugin so that it is compatible with the latest version of IF.

**Comment by chargao** [comment]
Some clarifying questions:
* Is [the Plugins section](https://github.com/Green-Software-Foundation/if/blob/main/Refactor-migration-guide.md#plugins) the relevant section from the migration guide?
* Is src/lib/datadog-importer/index.ts the file that needs to be updated?
*

**Comment by moin-oss** [comment]
Yes to both!  The `sample-input.yml` file, and possibly the `sample-output.yml` file, needs to be updated as well, but that could be done as part of another issue.

**Comment by eforkin** [comment]
Was able to get around to this myself, assigning me as the assignee
