### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by moin-oss** [moin-oss/datadog-importer#6]
Update the README to better reflect how the plugin works.  See for example https://github.com/jmcook1186/carbon-intensity-plugin

**Comment by sebasSerrano12** [comment]
I'd like to contribute to the README plz.

**Comment by moin-oss** [comment]
> I'd like to contribute to the README plz.

Thanks! I've added you to the the list of collaborators so you'll be able to open a branch and then a pull request.  We appreciate the help!
